let platform = ''
// #ifdef  MP-WEIXIN
platform = 'mini'
// #endif
// #ifdef  MP-ALIPAY
platform = 'ali'
// #endif
// #ifdef  MP-BAIDU
platform = 'baidu'
// #endif
// #ifdef  MP-TOUTIAO	
platform = 'toutiao'
// #endif
// #ifdef  H5
const isWechat = () => {
	return String(navigator.userAgent.toLowerCase().match(/MicroMessenger/i)) == "micromessenger";
}
platform = isWechat() ? 'weChat' : 'h5'
// #endif
let t = 'channelApi/',
	api = {
		platform,
		config: t + 'config/config',
		login: t + 'login/login', //获取code
		wechatLogin: t + 'wechat/login', //获取code
		jm: t + 'login/decrypt',
		xgyh: t + 'login/save-user',
		pay: t + 'pay/pay',
		shopGoodsInfo: t + 'good/get-product-list',
		qtsjjh: t + 'shop/window-collection',
		WxSign: t + 'wechat/get-wx-sign',
		WxUpload: t + 'WxUpload',
		layout: t + 'config/get-drag-row', //拖拽数据
		xggwc: t + 'order/save-shop-car',
		wdgwc: t + 'order/get-car-list',
		qkgwc: t + 'order/del-car',
		spxq: t + 'good/get-good-detail',
		bcshdz: t + 'member/save-user-address',
		wdshdz: t + 'member/my-address',
		scshdz: t + 'member/del-user-address',
		xzshdz: t + 'member/receiving-address',
		wmxzsj: t + 'order/store-time',
		wmxd: t + 'order/save-order',
		ddlb: t + 'order/order-list',
		ddsz: t + 'order/order-set',
		wmddqx: t + 'order/cancel-order',
		wmddcd: t + 'order/reminder',
		wmddtk: t + 'order/refund',
		wmddsh: t + 'order/receiving',
		wmddxq: t + 'order/order-info',
		wmmbxx: t + 'config/template-list',
		zjdp: t + 'shop/lately-store',
		zbtdz: t + 'config/coordinate-to-add',
		bzzx: t + 'member/get-helps-list',
		bzxq: t + 'member/get-helps-detail',
		ggxq: t + 'good/get-good-oper',
		ptgg: t + 'config/get-article-list',
		fwjl: t + 'cloud/visit-collect',
		wmxdbd: t + 'order/order-muster',
		xcxm: t + 'config/get-code',
		tzssp: t + 'good/good-rank-type',
		zblb: t + 'config/get-mini-live',
		lqzx: t + 'coupon/coupon-list',
		lqyhq: t + 'coupon/receive-coupon',
		yhqxq: t + 'coupon/coupon-info',
		wdyhq: t + 'coupon/my-coupon',
		kyyhq: t + 'coupon/available-coupon',
		czgz: t + 'member/recharge-rule',
		czxd: t + 'member/recharge-order',
		yemx: t + 'member/balance-details',
		qd: t + 'sign-in/sign',
		bzqd: t + 'sign-in/week-sign-record',
		wdqdsj: t + 'sign-in/my-sign',
		wdqdjl: t + 'sign-in/my-sign-record',
		jfsplb: t + 'integral-shop/goods-list',
		jffl: t + 'integral-shop/goods-type-list',
		jfspxq: t + 'integral-shop/goods-info',
		jfscztlb: t + 'integral-shop/self-list',
		jfspxd: t + 'integral-shop/save-integral-order',
		jfdd: t + 'integral-shop/my-integral-order',
		jfddxq: t + 'integral-shop/integral-order-info',
		jfmx: t + 'member/integral-details',
		jfqrsh: t + 'integral-shop/modify-order',
		xkzx: t + 'member/new',
		zfyl: t + 'order/pay-politely',
		scyl: t + 'member/collection',
		sctp: t + 'config/upload',
		zxlb: t + 'config/information',
		zxxq: t + 'config/information-info',
		lqtcyhq: t + 'shop/receive-window-coupon',
		cssj: t + 'shop/get-city',
		dwcs: t + 'shop/coordinate-to-add',
		dplb: t + 'shop/store-list',
		scjk: t + 'member/save-collection',
		dplbsc: t + 'shop/collection-store-list',
		dplbss: t + 'shop/search-store',
		sytchj: t + 'member/window',
		lqfqb: t + 'member/receive-issue-coupons',
		qbxq: t + 'roll-bag/roll-bag-info',
		qbxd: t + 'roll-bag/roll-bag-order',
		qbgmjl: t + 'roll-bag/order-list',
		dhm: t + 'member/exchange-code',
		spss: t + 'good/select-good',
		syxd: t + 'cashier/save-cashier',
		kcxd: t + 'in-store/save-fast-order',
		kclb: t + 'in-store/my-fast-order',
		kcddcz: t + 'in-store/refund-fast',
		kcddxq: t + 'in-store/fast-order-info',
		dmlb: t + 'cashier/my-cashier',
		dmxq: t + 'cashier/cashier-order-info',
		zqqcm: t + 'order/meal-code',
		smjhm: t + 'in-store/get-code-info',
		tsczxq: t + 'in-store/table-info',
		tspdbxp: t + 'in-store/shop-car-require',
		tsxdd: t + 'in-store/save-in-store-order',
		tsdd: t + 'in-store/my-in-store-order',
		tsddxq: t + 'in-store/in-store-order-info',
		tsgwc: t + 'in-store/my-in-store-car',
		tsqxdd: t + 'in-store/close-in-order',
		tsjc: t + 'in-store/add-food',
		zzsj: t + 'order/production-time',
		hydj: t + 'vip-card/level-list',
		hykk: t + 'vip-card/receive-card',
		jhhyk: t + 'vip-card/activate-membership',
		hykcs: t + 'vip-card/member-card-parameter',
		hykczz: t + 'member/growth-details',
		ffhykqy: t + 'pay-vip/rights-list',
		ffhysj: t + 'pay-vip/vip-info',
		ffhygmjl: t + 'pay-vip/my-order',
		ffhyxd: t + 'pay-vip/vip-order',
		owni: t + 'old-with-new/index',
		ownrank: t + 'old-with-new/rank',
		ownilist: t + 'old-with-new/invitation-list',
		orderRep: t + 'order/replace-order',
		memberBW: t + 'member/bonus-withdrawal',
		memberWL: t + 'member/withdrawal-list',
		distributionAD: t + 'distribution/apply-distribution',
		distributionGO: t + 'distribution/get-offline',
		distributionIndex: t + 'distribution/index',
		distributionDO: t + 'distribution/distribution-order',
		bcjc: t + 'wine-storage/save-storage',
		jcfl: t + 'wine-storage/storage-brand',
		jclb: t + 'wine-storage/storage-list',
		jcqj: t + 'wine-storage/save-take-record',
		jclqlb: t + 'wine-storage/storage-take-list',
		getStoreConfig: t + 'config/get-store-config',
		pdcz: t + 'queuing/queuing-type',
		pdxd: t + 'queuing/take-number',
		pdxq: t + 'queuing/take-number-info',
		qxpd: t + 'queuing/modify-take-number',
		pdlb: t + 'queuing/my-take-number',
		yyxx: t + 'reserve/appointment-options',
		yyxd: t + 'reserve/save-appointment-order',
		wdyy: t + 'reserve/my-appointment-order',
		yyxq: t + 'reserve/appointment-order-info',
		qxyy: t + 'reserve/operation-appointment-order',
		ispop: t + 'dividend/is-pop',
		divreceive: t + 'dividend/receive',
		divinfo: t + 'dividend/info',
		divlist: t + 'dividend/receive-list',
		OrderEvaluate: t + 'order/evaluate',
		EvaluateList: t + 'order/evaluate-list',
		Lable: t + 'order/label-list',
		getDiscount: t + 'cashier/get-discount',
		mealCode: t + 'coupon/meal-code',
		collectList: t + 'member/collect-list',
	};
export default api
